#! /usr/bin/env python

import sys, re, string

lines = sys.stdin.readlines()

for line in lines:
  ls = re.split('\s+', line)
  # print ls
  # unsigned char _P1IN;     /* 0x0020 Input                 */
  # ->   "0x0000":'_IE1',
  print '  "' + ls[4] + '":\'' + ls[2].rstrip(';') + '\',' 
  # print '  ' + ls[-3] + ';\t' + '/* ' + ls [-2] + ' ' + ' '.join(ls[0:-3]) + '\t*/'


